### PR TITLE
Issue #33 Issue #51

### PR DESCRIPTION
**Pull request by keiyou**
Issue #33。 I just found that Issue #51 is kind of the same stuff, so I added it.
Adds Background Music and buttons on the main menu to play or pause it.
Adds Ending  Music
Adds fish-eating sound effects and jellyfish-eating sound effects

### CODE REVIEW

**Comment by keiyou** [comment]
F16 @keiyou @zihengsong 
mentor: @asyung

**Comment by asyung** [comment]
This pull request introduces 77 new issues on codacy:
https://www.codacy.com/app/asyung888/cs56-games-fish-animation/pullRequest?prid=415460#newIssuesView

**Comment by keiyou** [comment]
I don't think all those 77 issues are new, because most of them have been there before we started to work on the sound stuffs. There seems to be only three new issues comes with my EffectSound.java and I have fixed them.

**Comment by keiyou** [comment]
Done!

**Pull request merged**
